v {xschem version=3.4.5 file_version=1.2
}
G {}
K {}
V {}
S {}
E {}
T {CACE testbench osc_transient} -1220 -660 0 0 0.6 0.6 {}
T {Drawn by R. Timothy Edwards
November 27, 2023
Template by Aquiles Viza
Open sourced under Apache 2.0 license} 40 -580 0 0 0.4 0.4 {}
N -1090 -210 -1030 -210 {
lab=GND}
N -1140 -210 -1090 -210 {
lab=GND}
N -530 -150 -530 -120 {
lab=vss}
N -530 -300 -530 -270 {
lab=vdd}
N -1030 -300 -1030 -270 {
lab=vss}
N -1120 -300 -1120 -270 {
lab=vdd}
N -630 -20 -560 -20 { lab=out}
N -630 -40 -630 -20 { lab=out}
N -670 -70 -650 -70 { lab=SENS_IN}
N -630 -190 -630 -100 {
lab=SENS_IN}
N -560 -20 -400 -20 {
lab=out}
N -400 -180 -400 -20 {
lab=out}
N -470 -180 -400 -180 {
lab=out}
N -470 -230 -360 -230 {
lab=#net1}
N -470 -190 -360 -190 {
lab=#net2}
N -670 -120 -630 -120 {
lab=SENS_IN}
N -670 -120 -670 -70 {
lab=SENS_IN}
N -670 -340 -670 -300 { lab=vdd}
N -670 -260 -670 -220 { lab=vss}
N -680 -190 -590 -190 { lab=SENS_IN}
N -610 -280 -610 -230 { lab=#net3}
N -710 -280 -670 -280 { lab=SENS_IN}
N -710 -190 -680 -190 { lab=SENS_IN}
N -630 -280 -610 -280 { lab=#net3}
N -610 -230 -590 -230 { lab=#net3}
N -710 -280 -710 -190 { lab=SENS_IN}
N -670 -320 -650 -320 {
lab=vdd}
N -650 -320 -650 -290 {
lab=vdd}
C {devices/vsource.sym} -1030 -240 0 0 {name=vvss value="DC 0" savecurrent=false}
C {devices/lab_wire.sym} -1120 -290 0 1 {name=p11 sig_type=std_logic lab=vdd}
C {devices/lab_wire.sym} -1030 -290 0 1 {name=p24 sig_type=std_logic lab=vss}
C {devices/lab_wire.sym} -400 -110 0 0 {name=p25 sig_type=std_logic lab=out}
C {devices/vsource.sym} -1120 -240 0 0 {name=vvdd value="DC 2.0" savecurrent=false}
C {devices/code_shown.sym} -460 -540 0 0 {name=CONTROL only_toplevel=false value="
.ic v(SENS_IN)=0
.save v(out)
.control
tran 0.1n 15u 10u

meas tran period
+ TRIG v(out) VAL=0.9 RISE=1
+ TARG v(out) VAL=0.9 RISE=2

let freq = 1/period
print freq

plot out
.endc
"}
C {devices/code_shown.sym} -1220 -550 0 0 {name=SETUP
only_toplevel=false
place=header
value="* CACE gensim simulation file \{filename\}_\{N\}
* Generated by CACE gensim, Efabless Corporation (c) 2023

.option TEMP=130
* Flag unsafe operating conditions (exceeds models' specified limits)
.option warn=1
"}
C {devices/gnd.sym} -1140 -210 0 0 {name=l1 lab=GND}
C {devices/lab_wire.sym} -530 -120 2 1 {name=p3 sig_type=std_logic lab=vss}
C {devices/lab_wire.sym} -530 -300 0 1 {name=p4 sig_type=std_logic lab=vdd}
C {symbol/OSC.sym} -650 -210 0 0 {name=X1}
C {devices/code.sym} -580 -710 0 0 {name=MODELS_TT
only_toplevel=true
spice_ignore=0
format="tcleval( @value )"
value="
*.lib $env(PDK_ROOT)/$env(PDK)/libs.tech/combined/sky130.lib.spice tt
.lib $env(PDK_ROOT)/$env(PDK)/libs.tech/ngspice/sky130.lib.spice.tt.red tt

.include $env(PDK_ROOT)/$env(PDK)/libs.ref/sky130_fd_sc_hd/spice/sky130_fd_sc_hd.spice
"}
C {devices/code.sym} -340 -710 0 0 {name=MODELS_FF
only_toplevel=true
spice_ignore=1
format="tcleval( @value )"
value="
*.lib $env(PDK_ROOT)/$env(PDK)/libs.tech/combined/sky130.lib.spice ff
.lib $env(PDK_ROOT)/$env(PDK)/libs.tech/ngspice/sky130.lib.spice.ff.red ff
.include $env(PDK_ROOT)/$env(PDK)/libs.ref/sky130_fd_sc_hd/spice/sky130_fd_sc_hd.spice
"}
C {devices/code.sym} -460 -710 0 0 {name=MODELS_SS
only_toplevel=true
spice_ignore=1
format="tcleval( @value )"
value="
*.lib $env(PDK_ROOT)/$env(PDK)/libs.tech/combined/sky130.lib.spice ss
.lib $env(PDK_ROOT)/$env(PDK)/libs.tech/ngspice/sky130.lib.spice.ss.red ss
.include $env(PDK_ROOT)/$env(PDK)/libs.ref/sky130_fd_sc_hd/spice/sky130_fd_sc_hd.spice
"}
C {devices/lab_pin.sym} -560 -20 3 0 {name=l9 sig_type=std_logic lab=REF_IN}
C {sky130_fd_pr/res_high_po_5p73.sym} -630 -70 0 0 {name=R1
W=5.73
L=8
model=res_high_po_5p73
spiceprefix=X
mult=1}
C {devices/lab_pin.sym} -630 -160 0 0 {name=l2 sig_type=std_logic lab=SENS_IN}
C {symbol/PASSGATE.sym} -670 -280 0 0 {name=XPG}
C {devices/lab_pin.sym} -670 -340 0 0 {name=l16 sig_type=std_logic lab=vdd}
C {devices/lab_pin.sym} -670 -220 0 0 {name=l17 sig_type=std_logic lab=vss}
