v {xschem version=3.4.5 file_version=1.2
}
G {}
K {}
V {}
S {}
E {}
T {CACE testbench osc_transient} -1220 -660 0 0 0.6 0.6 {}
T {Drawn by R. Timothy Edwards
November 27, 2023
Template by Aquiles Viza
Open sourced under Apache 2.0 license} 40 -580 0 0 0.4 0.4 {}
N -1090 -210 -1030 -210 {
lab=GND}
N -1140 -210 -1090 -210 {
lab=GND}
N -1030 -300 -1030 -270 {
lab=vss}
N -1120 -300 -1120 -270 {
lab=vdd}
N -470 -110 -470 -80 {
lab=vss}
N -470 -260 -470 -230 {
lab=vdd}
N -570 20 -500 20 { lab=out}
N -570 0 -570 20 { lab=out}
N -610 -30 -590 -30 { lab=SENS_IN}
N -570 -150 -570 -60 {
lab=SENS_IN}
N -500 20 -340 20 {
lab=out}
N -340 -140 -340 20 {
lab=out}
N -410 -140 -340 -140 {
lab=out}
N -410 -190 -300 -190 {
lab=#net1}
N -410 -150 -300 -150 {
lab=#net2}
N -610 -80 -570 -80 {
lab=SENS_IN}
N -610 -80 -610 -30 {
lab=SENS_IN}
N -610 -300 -610 -260 { lab=vdd}
N -610 -220 -610 -180 { lab=vss}
N -620 -150 -530 -150 { lab=SENS_IN}
N -550 -240 -550 -190 { lab=#net3}
N -650 -240 -610 -240 { lab=SENS_IN}
N -650 -150 -620 -150 { lab=SENS_IN}
N -570 -240 -550 -240 { lab=#net3}
N -550 -190 -530 -190 { lab=#net3}
N -650 -240 -650 -150 { lab=SENS_IN}
N -610 -280 -590 -280 {
lab=vdd}
N -590 -280 -590 -250 {
lab=vdd}
C {devices/vsource.sym} -1030 -240 0 0 {name=vvss value="DC \{vvss\}" savecurrent=false}
C {devices/lab_wire.sym} -1120 -290 0 1 {name=p11 sig_type=std_logic lab=vdd}
C {devices/lab_wire.sym} -1030 -290 0 1 {name=p24 sig_type=std_logic lab=vss}
C {devices/vsource.sym} -1120 -240 0 0 {name=vvdd value="DC \{vvdd\}" savecurrent=false}
C {devices/code_shown.sym} -460 -540 0 0 {name=CONTROL only_toplevel=false value="
.ic v(SENS_IN)=0
.save v(out)
.control
tran 0.1n 11u 10u

meas tran period
+ TRIG v(out) VAL=0.9 RISE=1
+ TARG v(out) VAL=0.9 RISE=2

let freq = 1/period

echo $&freq > \{simpath\}/\{filename\}_\{N\}.data
quit
.endc
"}
C {devices/code_shown.sym} -1220 -550 0 0 {name=SETUP
only_toplevel=false
place=header
value="* CACE gensim simulation file \{filename\}_\{N\}
* Generated by CACE gensim, Efabless Corporation (c) 2023

.include \{DUT_path\}

.option TEMP=\{temperature\}
* Flag unsafe operating conditions (exceeds models' specified limits)
.option warn=1
"}
C {devices/gnd.sym} -1140 -210 0 0 {name=l1 lab=GND}
C {devices/lab_wire.sym} -340 -70 0 0 {name=p25 sig_type=std_logic lab=out}
C {devices/lab_wire.sym} -470 -80 2 1 {name=p3 sig_type=std_logic lab=vss}
C {devices/lab_wire.sym} -470 -260 0 1 {name=p4 sig_type=std_logic lab=vdd}
C {symbol/OSC.sym} -590 -170 0 0 {name=X1}
C {devices/lab_pin.sym} -500 20 3 0 {name=l9 sig_type=std_logic lab=REF_IN}
C {sky130_fd_pr/res_high_po_5p73.sym} -570 -30 0 0 {name=R1
W=5.73
L=8
model=res_high_po_5p73
spiceprefix=X
mult=1}
C {devices/lab_pin.sym} -570 -120 0 0 {name=l2 sig_type=std_logic lab=SENS_IN}
C {symbol/PASSGATE.sym} -610 -240 0 0 {name=XPG}
C {devices/lab_pin.sym} -610 -300 0 0 {name=l16 sig_type=std_logic lab=vdd}
C {devices/lab_pin.sym} -610 -180 0 0 {name=l17 sig_type=std_logic lab=vss}
C {devices/code.sym} -400 -730 0 0 {name=MODELS
only_toplevel=true
spice_ignore=0
format="tcleval( @value )"
value="
.lib $env(PDK_ROOT)/$env(PDK)/libs.tech/combined/sky130.lib.spice \{corner\}

.include $env(PDK_ROOT)/$env(PDK)/libs.ref/sky130_fd_sc_hd/spice/sky130_fd_sc_hd.spice
"}
